name: cambodia_geography
description: cambodia geo
publish_to: none
version: 1.1.4+13
environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.3
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^5.0.2
  flutter_sticky_header: ^0.6.0
  fuzzy: ^0.4.0-nullsafety.0
  provider: ^6.0.1
  shared_preferences: ^2.0.6
  swipeable_page_route: ^0.2.2
  scroll_to_index: ^2.0.0
  rect_getter: ^1.0.0
  http: ^0.13.3
  http_interceptor: ^1.0.1
  weather: ^2.0.1
  firebase_core: ^1.4.0
  flutter_facebook_auth: ^3.5.0
  google_sign_in: ^5.0.5
  firebase_auth: ^3.0.1
  shimmer: ^2.0.0
  cached_network_image: ^3.1.0
  image_picker: ^0.8.2
  image_cropper: ^1.4.1
  delta_markdown: ^0.3.0
  page_indicator: ^0.4.1
  flutter_markdown: ^0.6.2
  intl: ^0.17.0
  animations: ^2.0.1
  after_layout: ^1.1.0
  japx:
    git:
      url: "https://github.com/niptict-g6/flutter-plugins-japx.git"
      ref: master
  font_awesome_flutter: ^9.1.0
  flutter_signin_button: ^2.0.0
  adaptive_dialog: ^1.1.0
  lottie: ^1.1.0
  geolocator: ^8.0.1
  geocoding: ^2.0.0
  flutter_cache_manager: ^3.1.2
  styled_text: ^4.0.0+1
  flutter_countdown_timer: ^4.1.0
  open_mail_app: ^0.4.1
  pausable_timer: ^1.0.0+1
  avatar_glow: ^2.0.1
  fluttertoast: ^8.0.8
  settings_ui: ^1.0.0
  google_maps_flutter: ^2.0.8
  carousel_slider: ^4.0.0
  uni_links: ^0.5.1
  flutter_google_places: # ^0.3.0
    path: flutter_google_places
  easy_localization: ^3.0.0
  about: ^2.0.1
  dio: ^4.0.0
  csv: ^5.0.0
  package_info: ^2.0.2
  url_launcher: ^6.0.10
  webview_flutter: ^3.0.0
  store_redirect: ^2.0.0
  in_app_review: ^2.0.3
  timeago: ^3.1.0
  visibility_detector: ^0.2.0
  recase: ^4.0.0
  firebase_remote_config: ^1.0.2
  connectivity: ^3.0.6
  in_app_update: ^2.0.0
  flutter_quill: ^2.3.0

dev_dependencies:
  build_runner: ^2.1.5
  json_serializable: ^6.1.1
  change_app_package_name: ^1.0.0
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/lotties/
    - assets/images/provinces/
    - assets/images/helper_image/
    - assets/translations/
  fonts:
    - family: Lora
      fonts:
        - asset: assets/fonts/Lora/Lora-Bold.ttf
        - asset: assets/fonts/Lora/Lora-BoldItalic.ttf
        - asset: assets/fonts/Lora/Lora-Italic.ttf
        - asset: assets/fonts/Lora/Lora-Medium.ttf
        - asset: assets/fonts/Lora/Lora-MediumItalic.ttf
        - asset: assets/fonts/Lora/Lora-Regular.ttf
        - asset: assets/fonts/Lora/Lora-SemiBold.ttf
        - asset: assets/fonts/Lora/Lora-SemiBoldItalic.ttf
    - family: Battambang
      fonts:
        - asset: assets/fonts/Battambang/Battambang-Bold.ttf
        - asset: assets/fonts/Battambang/Battambang-Regular.ttf
