name: cambodia_geography
description: cambodia geo
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies: 
  flutter:
    sdk: flutter
  flutter_secure_storage: ^4.2.0
  flutter_sticky_header: ^0.6.0
  fuzzy: ^0.3.0
  provider: ^5.0.0
  shared_preferences: ^2.0.6
  swipeable_page_route: ^0.2.2

dev_dependencies:
  build_runner: ^2.0.6
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: Lora
      fonts:
        - asset: assets/fonts/Lora/Lora-Bold.ttf
        - asset: assets/fonts/Lora/Lora-BoldItalic.ttf
        - asset: assets/fonts/Lora/Lora-Italic.ttf
        - asset: assets/fonts/Lora/Lora-Medium.ttf
        - asset: assets/fonts/Lora/Lora-MediumItalic.ttf
        - asset: assets/fonts/Lora/Lora-Regular.ttf
        - asset: assets/fonts/Lora/Lora-SemiBold.ttf
        - asset: assets/fonts/Lora/Lora-SemiBoldItalic.ttf
    - family: Battambang
      fonts:
        - asset: assets/fonts/Battambang/Battambang-Bold.ttf
        - asset: assets/fonts/Battambang/Battambang-Regular.ttf